### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by bettercallazamat** [Zubenna/tic-tac-toe-project#6]
Consider the next points for separation of game logic into classes:
1) main.rb file should not have classes, this file to start a game and create instances of your classes and it should be located in bin directory; also you will need to import files with classes using "require relative"
2) You might create board, user, etc classes in separate files and each one should have initialize method with instance var about your board and users; they should be in lib directory
3) Do not forget to validate user inputs on game steps like turn and username.

**Comment by Zubenna** [comment]
Recommendations have been implemented
